use std::{fs, io::Read, path::PathBuf};

const FONT_URL: &str =
    "https://github.com/google/material-design-icons/raw/master/font/MaterialIcons-Regular.ttf";

const CODEPOINTS_URL: &str = "https://raw.githubusercontent.com/google/material-design-icons/master/font/MaterialIcons-Regular.codepoints";

fn download_bytes(url: &str) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
    let resp = ureq::get(url).call()?;
    let mut bytes = Vec::new();
    resp.into_body().into_reader().read_to_end(&mut bytes)?;
    Ok(bytes)
}

/// `zoom_in` → `ICON_ZOOM_IN`, `3d_rotation` → `ICON_3D_ROTATION`
fn icon_const_name(icon_name: &str) -> String {
    format!("ICON_{}", icon_name.to_uppercase())
}

fn generate_consts(codepoints: &str) -> String {
    let mut out = String::from("// Auto-generated by build.rs — do not edit.\n");
    let mut seen = std::collections::HashSet::new();
    for line in codepoints.lines() {
        let mut parts = line.split_whitespace();
        let (Some(name), Some(hex)) = (parts.next(), parts.next()) else {
            continue;
        };
        let const_name = icon_const_name(name);
        if !seen.insert(const_name.clone()) {
            continue; // skip duplicates (upstream codepoints file has a few)
        }
        out.push_str(&format!(
            "pub const {}: &str = \"\\u{{{}}}\";\n",
            const_name, hex,
        ));
    }
    out
}

fn main() {
    println!("cargo::rustc-check-cfg=cfg(has_material_icons)");
    println!("cargo::rustc-check-cfg=cfg(has_custom_font)");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=EGUI_SHADCN_CUSTOM_FONT_URL");
    println!("cargo:rerun-if-env-changed=EGUI_SHADCN_CUSTOM_FONT_NAME");
    println!("cargo:rerun-if-env-changed=EGUI_SHADCN_CODEPOINTS_PATH");
    println!("cargo:rerun-if-env-changed=EGUI_SHADCN_FONT_PATH");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let target_arch = std::env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();

    // ── Icon codepoints → OUT_DIR/icon_consts.rs ─────────────────────────────
    // EGUI_SHADCN_CODEPOINTS_PATH: pre-fetched file (e.g. from Nix FOD).
    let cp_path = out_dir.join("MaterialIcons-Regular.codepoints");
    if !cp_path.exists() {
        if let Ok(src) = std::env::var("EGUI_SHADCN_CODEPOINTS_PATH") {
            fs::copy(&src, &cp_path).expect("copy codepoints from EGUI_SHADCN_CODEPOINTS_PATH");
        } else {
            eprintln!("[egui_components] downloading Material Icons codepoints…");
            let bytes = download_bytes(CODEPOINTS_URL).unwrap_or_else(|e| {
                panic!(
                    "[egui_components] could not download Material Icons codepoints: {e}\n\
                     Internet access required on the first build (or after `cargo clean`).\n\
                     For offline builds set EGUI_SHADCN_CODEPOINTS_PATH to a pre-fetched copy."
                )
            });
            fs::write(&cp_path, &bytes).expect("write codepoints");
            eprintln!(
                "[egui_components] codepoints cached → {}",
                cp_path.display()
            );
        }
    }
    let codepoints = fs::read_to_string(&cp_path).expect("read codepoints");
    fs::write(out_dir.join("icon_consts.rs"), generate_consts(&codepoints))
        .expect("write icon_consts.rs");

    // ── Custom text font ──────────────────────────────────────────────────────
    // Configure via env vars before building:
    //   EGUI_SHADCN_CUSTOM_FONT_URL=https://…/Font.ttf
    //   EGUI_SHADCN_CUSTOM_FONT_NAME=Inter   (default: "CustomFont")
    if let Ok(url) = std::env::var("EGUI_SHADCN_CUSTOM_FONT_URL") {
        let font_name = std::env::var("EGUI_SHADCN_CUSTOM_FONT_NAME")
            .unwrap_or_else(|_| "CustomFont".to_string());

        let custom_ttf = out_dir.join("custom_font.ttf");
        if !custom_ttf.exists() {
            eprintln!("[egui_components] downloading custom font '{font_name}'…");
            match download_bytes(&url) {
                Ok(bytes) => {
                    fs::write(&custom_ttf, &bytes).expect("write custom font");
                    eprintln!(
                        "[egui_components] custom font saved → {}",
                        custom_ttf.display()
                    );
                }
                Err(e) => {
                    eprintln!("[egui_components] WARNING: could not download custom font: {e}");
                }
            }
        }

        if custom_ttf.exists() {
            // Write font name as a generated constant so the lib can read it.
            fs::write(
                out_dir.join("custom_font_name.rs"),
                format!("pub const CUSTOM_FONT_NAME: &str = {:?};\n", font_name),
            )
            .expect("write custom_font_name.rs");
            println!("cargo:rustc-cfg=has_custom_font");
        }
    }

    // ── Material Icons font (native only — WASM fetches at runtime) ──────────
    if target_arch == "wasm32" {
        return;
    }

    let ttf_path = out_dir.join("MaterialIcons-Regular.ttf");
    if !ttf_path.exists() {
        if let Ok(src) = std::env::var("EGUI_SHADCN_FONT_PATH") {
            fs::copy(&src, &ttf_path).expect("copy font from EGUI_SHADCN_FONT_PATH");
        } else {
            eprintln!("[egui_components] downloading Material Icons font…");
            match download_bytes(FONT_URL) {
                Ok(bytes) => {
                    fs::write(&ttf_path, &bytes).expect("write font");
                    eprintln!("[egui_components] font saved → {}", ttf_path.display());
                }
                Err(e) => {
                    eprintln!("[egui_components] WARNING: could not download font: {e}");
                }
            }
        }
    }

    if ttf_path.exists() {
        println!("cargo:rustc-cfg=has_material_icons");
    }
}
