[package]
name    = "egui-shadcn"
version = "0.1.0"
edition = "2024"
build   = "build.rs"

[features]
default    = ["lang-en-us", "lang-pt-br"]
lang-en    = ["i18n/lang-en"]
lang-en-us = ["i18n/lang-en-us"]
lang-pt    = ["i18n/lang-pt"]
lang-pt-br = ["i18n/lang-pt-br"]

[dependencies]
egui = { workspace = true }
i18n = { path = "../i18n/i18n" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3"

[dev-dependencies]
skrifa = { version = "0.40", features = ["std", "autohint_shaping"] }

[build-dependencies]
ureq = { version = "2", features = ["tls"] }
