[package]
name    = "demo"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "demo-native"
path = "src/main.rs"

[features]
default    = ["lang-en-us", "lang-pt-br"]
lang-en    = ["i18n/lang-en", "egui_sc/lang-en"]
lang-en-us = ["i18n/lang-en-us", "egui_sc/lang-en-us"]
lang-pt    = ["i18n/lang-pt", "egui_sc/lang-pt"]
lang-pt-br = ["i18n/lang-pt-br", "egui_sc/lang-pt-br"]

[dependencies]
egui_sc = { path = "../egui_sc" }
egui    = { workspace = true }
i18n    = { path = "../i18n/i18n" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
eframe = { workspace = true, features = ["default_fonts", "glow", "x11", "wayland"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
eframe               = { workspace = true, features = ["default_fonts", "glow"] }
wasm-bindgen         = "0.2"
wasm-bindgen-futures = "0.4"
web-sys              = { version = "0.3", features = ["Document", "HtmlCanvasElement", "Window", "Response"] }
js-sys               = "0.3"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"
skrifa            = { version = "0.42", features = ["std", "autohint_shaping"] }

[build-dependencies]
ureq = { version = "2", features = ["tls"] }
